### PR TITLE
Add scroll to top functionality

### PR DESCRIPTION
**Pull request by geramirez**
I was able to get the feature working, but I'm not sure how we want to proceed with compiling css and js assets.

The css assets seemed to work fine when I used gulp, the js assets didn't have a task that copied them over. For now I put them into a <script/> tag but ideally, it gulp should add them to the assets right?

thoughts, @matthewcrist

### CODE REVIEW

**Comment by matthewcrist** [comment]
We'll probably need to have a second JS file for our custom stuff. That should get built separately from the USWDS JS.

**Comment by matthewcrist** [comment]
I updated the build process to build the JS for the USWDS. Made a couple tweaks to the button too. Changes are:

- Using USWDS utilities for styling
- Not showing until the user has scrolled a couple of pages
- Change to a link since it's navigating the page

**Comment by geramirez** [comment]
@matthewcrist so I ended up removing the footer-return option. In the original benjamin the option made sense because you had the ability to sort it. With a sticky return to top, the sorting doen't apply. 

We might have remove some options from the database to make it complete disapear, though.

I also, deleted some js files that I though might be unused.

**Comment by matthewcrist** [comment]
👍

**Pull request merged**
